# Generated by Django 6.1.1 on 2026-09-23 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_capacity_liters', models.FloatField(default=10000.0)),
                ('tank_level_liters', models.FloatField(default=7800.0)),
                ('pump_status', models.CharField(default='Running', max_length=20)),
                ('system_mode', models.CharField(default='Auto', max_length=20)),
                ('pump_efficiency', models.FloatField(default=94.2)),
                ('pressure_psi', models.FloatField(default=42.5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=100)),
                ('target_liters', models.FloatField(default=250.0)),
                ('delivered_liters', models.FloatField(default=0.0)),
                ('flow_rate', models.FloatField(default=18.0)),
                ('valve_percent', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('Balanced', 'Balanced'), ('Throttled', 'Throttled'), ('Paused', 'Paused'), ('Completed', 'Completed')], default='Balanced', max_length=50)),
                ('order', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Farmer', 'Farmer'), ('Field Operator', 'Field Operator')], default='Farmer', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('assigned_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='accounts.zone')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flow_rate', models.FloatField()),
                ('delivered_snapshot', models.FloatField()),
                ('valve_percent', models.IntegerField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='accounts.zone')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
