# Generated by Django 6.1.1 on 2026-09-23 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['order', 'ward_number', 'id']},
        ),
        migrations.RemoveField(
            model_name='zone',
            name='crop',
        ),
        migrations.AddField(
            model_name='systemstate',
            name='chlorination_ppm',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='pumping_station',
            field=models.CharField(default='Municipal Headworks Pumping Station', max_length=150),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='tank_name',
            field=models.CharField(default='Central Elevated Storage Reservoir (ESR - जलकुंभ)', max_length=150),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='turbidity_ntu',
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='pressure_bar',
            field=models.FloatField(default=3.2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='household_id',
            field=models.CharField(blank=True, default='NP-W1-1042', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='household_name',
            field=models.CharField(blank=True, default='Patil Residence', max_length=100),
        ),
        migrations.AddField(
            model_name='zone',
            name='elevation_tier',
            field=models.CharField(choices=[('Lowland', 'Lowland (High Natural Pressure)'), ('Standard', 'Standard Elevation'), ('High-Altitude', 'High-Altitude Ridge (Low Natural Pressure)'), ('Tail-End', 'Tail-End Sector (Distance Loss)')], default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='zone',
            name='households_count',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='zone',
            name='sector_type',
            field=models.CharField(default='Residential', max_length=100),
        ),
        migrations.AddField(
            model_name='zone',
            name='supply_timing',
            field=models.CharField(default='06:00 AM - 08:30 AM', max_length=100),
        ),
        migrations.AddField(
            model_name='zone',
            name='ward_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='level',
            field=models.CharField(choices=[('critical', 'Critical (Pipe Burst / Severe Loss)'), ('warning', 'Warning (Low Pressure / Suction Pump Detected)'), ('info', 'Info (Supply Schedule / Tank Refill)')], default='warning', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='pressure_psi',
            field=models.FloatField(default=48.0),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='pump_efficiency',
            field=models.FloatField(default=95.4),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='tank_capacity_liters',
            field=models.FloatField(default=500000.0),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='tank_level_liters',
            field=models.FloatField(default=390000.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='assigned_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_residents', to='accounts.zone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Nagar Parishad Officer', 'Nagar Parishad Officer (Chief Water Engineer)'), ('Ward Line Inspector', 'Ward Line Inspector / Pump Operator'), ('Citizen / Household', 'Citizen / Household Resident (कुटुंब)'), ('Administrator', 'Nagar Parishad Officer'), ('Farmer', 'Citizen / Household'), ('Field Operator', 'Ward Line Inspector')], default='Nagar Parishad Officer', max_length=50),
        ),
        migrations.AlterField(
            model_name='zone',
            name='delivered_liters',
            field=models.FloatField(default=122000.0),
        ),
        migrations.AlterField(
            model_name='zone',
            name='flow_rate',
            field=models.FloatField(default=18.5),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='zone',
            name='target_liters',
            field=models.FloatField(default=125000.0),
        ),
        migrations.AlterField(
            model_name='zone',
            name='valve_percent',
            field=models.IntegerField(default=90),
        ),
    ]
