# Generated by Django 6.1.1 on 2026-09-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_zone_options_remove_zone_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemalert',
            name='category',
            field=models.CharField(choices=[('leak', 'Leak Detection'), ('overflow', 'Overflow Prevention'), ('abnormal', 'Abnormal Usage'), ('equity', 'Fair Distribution Equity'), ('system', 'System Telemetry')], default='equity', max_length=30),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='abnormal_usage_alerts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='dry_run_protection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='leak_detection_status',
            field=models.CharField(default='Normal (Zero Active Leaks)', max_length=50),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='overflow_guard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='overflow_status',
            field=models.CharField(default='Safe (<90%)', max_length=50),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='water_wastage_prevented_liters',
            field=models.FloatField(default=92500.0),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='is_anomaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='abnormal_usage_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='equity_score',
            field=models.FloatField(default=99.2),
        ),
        migrations.AddField(
            model_name='zone',
            name='leak_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='level',
            field=models.CharField(choices=[('critical', 'Critical (Pipe Burst / Overflow Risk)'), ('warning', 'Warning (Abnormal Draw / Low Pressure)'), ('info', 'Info (Fair Quota Achieved / Shift Start)')], default='warning', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='pumping_station',
            field=models.CharField(default='AquaFair Central Pumping Station', max_length=150),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='tank_name',
            field=models.CharField(default='Municipal Elevated Storage Reservoir (ESR)', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='household_id',
            field=models.CharField(blank=True, default='AF-W1-1042', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Municipal Officer', 'Municipal / Administrative Officer'), ('Field Technician', 'Field Technician / Ward Operator'), ('Citizen / Household', 'Citizen / Household Resident (कुटुंब)'), ('Administrator', 'Municipal / Administrative Officer'), ('Farmer', 'Citizen / Household'), ('Field Operator', 'Field Technician / Ward Operator')], default='Municipal Officer', max_length=50),
        ),
        migrations.AlterField(
            model_name='zone',
            name='delivered_liters',
            field=models.FloatField(default=122500.0),
        ),
        migrations.AlterField(
            model_name='zone',
            name='status',
            field=models.CharField(choices=[('Balanced', 'Balanced (Equitable Flow)'), ('Throttled', 'Throttled (Elevation/Equity Trim)'), ('Paused', 'Paused (Feeder Closed)'), ('Completed', 'Completed (Fair Quota Achieved)')], default='Balanced', max_length=50),
        ),
    ]
