# Generated by Django 6.1.1 on 2026-09-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_systemalert_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstate',
            name='contamination_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='contamination_status',
            field=models.CharField(default='Potable (Safe Drinking Quality)', max_length=100),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='ph_level',
            field=models.FloatField(default=7.2),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='tds_ppm',
            field=models.FloatField(default=185.0),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='water_quality_index',
            field=models.FloatField(default=96.4),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='water_temp_c',
            field=models.FloatField(default=24.2),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='category',
            field=models.CharField(choices=[('contamination', 'Water Contamination Detection'), ('leak', 'Leak Detection'), ('overflow', 'Overflow Prevention'), ('low_water', 'Low Water Levels'), ('abnormal', 'Abnormal Usage'), ('equity', 'Fair Distribution Equity'), ('system', 'System Telemetry')], default='equity', max_length=30),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='level',
            field=models.CharField(choices=[('critical', 'Critical (Pipe Burst / Contamination / Overflow)'), ('warning', 'Warning (Abnormal Draw / Low Water / Quality Shift)'), ('info', 'Info (Fair Quota Achieved / Shift Start)')], default='warning', max_length=20),
        ),
    ]
