# Generated by Django 6.1.1 on 2026-09-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_systemstate_contamination_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryreading',
            name='ph_level',
            field=models.FloatField(default=7.4),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='turbidity_ntu',
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name='zone',
            name='contamination_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='ph_level',
            field=models.FloatField(default=7.4),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='category',
            field=models.CharField(choices=[('contamination', 'Water Contamination Detection'), ('quality', 'Water Quality Monitoring'), ('leak', 'Leak Detection'), ('overflow', 'Overflow Prevention'), ('low_water', 'Low Water Levels'), ('abnormal', 'Abnormal Usage'), ('equity', 'Fair Distribution Equity'), ('system', 'System Telemetry')], default='equity', max_length=30),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='level',
            field=models.CharField(choices=[('critical', 'Critical (Pipe Burst / Contamination / Overflow Risk)'), ('warning', 'Warning (Abnormal Draw / Low Water / Quality Shift)'), ('info', 'Info (Fair Quota Achieved / Shift Start)')], default='warning', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='ph_level',
            field=models.FloatField(default=7.4),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='water_quality_index',
            field=models.FloatField(default=96.5),
        ),
    ]
