# Generated by Django 6.1.1 on 2026-09-23 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_telemetryreading_ph_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_id', models.CharField(max_length=50, unique=True)),
                ('owner_name', models.CharField(max_length=150)),
                ('address_or_lane', models.CharField(default='Lane 1', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('members_count', models.IntegerField(default=4)),
                ('daily_quota_liters', models.FloatField(default=540.0)),
                ('current_usage_liters', models.FloatField(default=380.0)),
                ('meter_status', models.CharField(default='Active', max_length=30)),
                ('abnormal_draw', models.BooleanField(default=False)),
                ('extra_water_granted', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='accounts.zone')),
            ],
            options={
                'ordering': ['zone', 'household_id'],
            },
        ),
        migrations.CreateModel(
            name='WaterDemandRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=150)),
                ('household_code', models.CharField(blank=True, default='', max_length=50)),
                ('extra_liters', models.FloatField(default=500.0)),
                ('reason', models.CharField(max_length=255)),
                ('urgency', models.CharField(choices=[('Normal', 'Normal (Event in 24-48 hrs)'), ('High', 'High Priority (Same-day requirement)'), ('Emergency', 'Emergency (Critical / Health need)')], default='Normal', max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved (Extra Quota Dispatched)'), ('Fulfilled', 'Fulfilled & Delivered'), ('Rejected', 'Rejected (Exceeds Head Capacity)')], default='Pending', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demand_requests', to='accounts.household')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_requests', to='accounts.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
