# Generated by Django 6.1.1 on 2026-09-28 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=50, unique=True)),
                ('citizen_name', models.CharField(default='Citizen Resident', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('ward_name', models.CharField(blank=True, default='', max_length=150)),
                ('ward_number', models.IntegerField(default=1)),
                ('location', models.CharField(default='Municipal Sector', max_length=255)),
                ('incident_type', models.CharField(default='Pipeline Leak / Burst', max_length=150)),
                ('priority', models.CharField(choices=[('Normal', 'Normal Priority'), ('High', 'High Priority (Major Loss)'), ('Emergency', 'Emergency / Health Hazard')], default='Normal', max_length=30)),
                ('status', models.CharField(choices=[('Pending Investigation', 'Pending Investigation'), ('Field Team Dispatched', 'Field Team Dispatched'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved & Pressure Normalized'), ('Closed', 'Closed')], default='Pending Investigation', max_length=50)),
                ('assigned_technician', models.CharField(blank=True, default='Unassigned', max_length=150)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('eta_minutes', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='accounts.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterTanker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_code', models.CharField(max_length=50, unique=True)),
                ('vehicle_no', models.CharField(default='MH-12-AQ-101', max_length=50)),
                ('driver_name', models.CharField(default='Municipal Driver', max_length=150)),
                ('driver_phone', models.CharField(blank=True, default='', max_length=30)),
                ('capacity_liters', models.FloatField(default=5000.0)),
                ('target_ward_name', models.CharField(blank=True, default='', max_length=150)),
                ('target_ward_number', models.IntegerField(default=1)),
                ('destination_location', models.CharField(default='Community Water Point', max_length=255)),
                ('requester_name', models.CharField(default='Municipal Desk', max_length=150)),
                ('purpose', models.CharField(default='Emergency potable distribution', max_length=255)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered & Filled'), ('Cancelled', 'Cancelled')], default='In Transit', max_length=30)),
                ('departure_time', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('target_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tankers', to='accounts.zone')),
            ],
            options={
                'ordering': ['-departure_time'],
            },
        ),
    ]
