# Generated by Django 5.2.8 on 2026-09-30 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_grievance_watertanker'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('Valve Technician', 'Valve Technician & Flow Attendant'), ('Field Supervisor', 'Field Supervisor / Nagar Parishad Inspector'), ('Security & Queue Escort', 'Security & Crowd Attendant'), ('Sanitation & Chlorination Crew', 'Sanitation & Chlorination Crew')], default='Valve Technician', max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('badge_id', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active on Duty'), ('Assigned', 'Assigned to Dispatch'), ('Off Duty', 'Off Duty / Standby')], default='Active', max_length=50)),
                ('ward_assignment', models.CharField(blank=True, default='All Wards', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FleetDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('experience_years', models.IntegerField(default=5)),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('Available', 'Available on Duty'), ('On Route', 'On Route / Driving'), ('Off Duty', 'Off Duty / Rest')], default='Available', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FleetTanker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=50, unique=True)),
                ('tanker_name', models.CharField(default='Aqua Tanker', max_length=150)),
                ('capacity_liters', models.FloatField(default=5000.0)),
                ('model_make', models.CharField(blank=True, default='Tata 1613 SE', max_length=100)),
                ('ownership_type', models.CharField(choices=[('Municipal Owned', 'Nagar Parishad Owned'), ('Contractor Leased', 'Contractor Leased')], default='Municipal Owned', max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available / Standby'), ('In Transit', 'In Transit / Dispatched'), ('Under Maintenance', 'Under Maintenance / Service')], default='Available', max_length=50)),
                ('fitness_expiry', models.DateField(blank=True, null=True)),
                ('gps_tracking_id', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vehicle_no'],
            },
        ),
        migrations.AddField(
            model_name='watertanker',
            name='team_members',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='household',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telemetryreading',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='waterdemandrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='watertanker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='watertanker',
            name='fleet_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='accounts.fleetdriver'),
        ),
        migrations.AddField(
            model_name='fleetdriver',
            name='assigned_tanker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_drivers', to='accounts.fleettanker'),
        ),
        migrations.AddField(
            model_name='watertanker',
            name='fleet_tanker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='accounts.fleettanker'),
        ),
    ]
