# Generated by Django 5.2.8 on 2026-10-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_dispatchteammember_fleetdriver_fleettanker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='is_hardware_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='tank_capacity_liters',
            field=models.FloatField(default=1000000.0),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='tank_level_liters',
            field=models.FloatField(default=780000.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Municipal Officer', 'Municipal / Administrative Officer'), ('Field Technician', 'Field Technician / Ward Operator'), ('Citizen / Household', 'Citizen / Household Resident (कुटुंब)'), ('Tanker Driver', 'Municipal Water Tanker Driver'), ('Dispatch Team Leader', 'Field Dispatch & Maintenance Team Leader'), ('Administrator', 'Municipal / Administrative Officer'), ('Farmer', 'Citizen / Household'), ('Field Operator', 'Field Technician / Ward Operator')], default='Municipal Officer', max_length=50),
        ),
    ]
