# Generated by Django 5.2.8 on 2026-10-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_zone_is_hardware_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstate',
            name='tank_capacity_liters',
            field=models.FloatField(default=2500000.0),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='tank_level_liters',
            field=models.FloatField(default=1950000.0),
        ),
    ]
